// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_340_W22SD_Labs.Data;

#nullable disable

namespace SD_340_W22SD_Labs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_340_W22SD_Labs.Models.Route", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<bool>("BicycleAccessible")
                        .HasColumnType("bit");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RampAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Number");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("SD_340_W22SD_Labs.Models.ScheduledStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RouteNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<int>("StopNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteNumber");

                    b.HasIndex("StopNumber");

                    b.ToTable("ScheduledStop");
                });

            modelBuilder.Entity("SD_340_W22SD_Labs.Models.Stop", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Number");

                    b.ToTable("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Labs.Models.ScheduledStop", b =>
                {
                    b.HasOne("SD_340_W22SD_Labs.Models.Route", "Route")
                        .WithMany("StopSchedules")
                        .HasForeignKey("RouteNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD_340_W22SD_Labs.Models.Stop", "Stop")
                        .WithMany("StopSchedules")
                        .HasForeignKey("StopNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Labs.Models.Route", b =>
                {
                    b.Navigation("StopSchedules");
                });

            modelBuilder.Entity("SD_340_W22SD_Labs.Models.Stop", b =>
                {
                    b.Navigation("StopSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
